version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name gittest --zip-file fileb://lambda.zip
      - aws lambda update-function-code --function-name suryapoc2 --zip-file fileb://secondlambda.zip
      - echo "DONE!!"
