Version:0.2
phases:
install:
runtime-versions:
python:3.11
commands:
    -echo "Installing dependencies..."
    -pip install -r requirements.txt -t lip
build:
commands:
    -echo "Zipping deployment package..."
    -cd lip-zip -r9 ../deployment_package.zip .
    -cd ..
    -zip -g deployment_package.zip lambda.py
post_build:
commands:
    -echo "Updating lambda function..."
    -echo lambda-function-code --function-name Testgit --zip-file fileb://deployment_package.zip
    -echo "DONE!!"
